/**
 * State layer: PRs, review requests, follow-ups, audit — REAL
 *
 * All upserts and queries are fully implemented against the real Postgres DB.
 * No mocks in this file — all functions hit the database.
 *
 * MOCK DATA NOTE: The `review_requests` rows in the current DB were inserted
 * manually (not from GitHub sync) to simulate 6 reviewers across 3 PRs.
 * The `follow_ups` rows were generated by the mock cadence fallback in
 * `agent.ts` (since the Ollama API is unreachable). In a real deployment
 * with a working LLM, the follow-up decisions would come from the LLM.
 */
import { db } from '../db/client.js';
import { upsertReviewer } from './repos.js';
import type { DB } from '../db/types.js';
import type { Selectable } from 'kysely';

type Pr = Selectable<DB['pull_requests']>;
type ReviewRequest = Selectable<DB['review_requests']>;
type Reviewer = Selectable<DB['reviewers']>;

export interface PrSnapshot {
  repoId: number;
  number: number;
  title: string;
  state: 'open' | 'closed';
  draft: boolean;
  authorLogin: string;
  headRef: string;
  baseRef: string;
  createdAtGithub: Date;
  updatedAtGithub: Date;
  mergeableState: string | null;
  mergeable: boolean | null;
  additions: number;
  deletions: number;
  changedFiles: number;
  commits: number;
  htmlUrl: string;
  body: string | null;
}

export async function upsertPr(snap: PrSnapshot): Promise<Pr> {
  const existing = await db
    .selectFrom('pull_requests')
    .selectAll()
    .where('repo_id', '=', snap.repoId)
    .where('number', '=', snap.number)
    .executeTakeFirst();

  if (existing) {
    return db
      .updateTable('pull_requests')
      .set({
        title: snap.title,
        state: snap.state,
        draft: snap.draft,
        author_login: snap.authorLogin,
        head_ref: snap.headRef,
        base_ref: snap.baseRef,
        updated_at_github: snap.updatedAtGithub,
        mergeable_state: snap.mergeableState,
        mergeable: snap.mergeable,
        additions: snap.additions,
        deletions: snap.deletions,
        changed_files: snap.changedFiles,
        commits: snap.commits,
        html_url: snap.htmlUrl,
        body: snap.body,
        last_synced_at: new Date(),
      })
      .where('id', '=', existing.id)
      .returningAll()
      .executeTakeFirstOrThrow();
  }

  return db
    .insertInto('pull_requests')
    .values({
      repo_id: snap.repoId,
      number: snap.number,
      title: snap.title,
      state: snap.state,
      draft: snap.draft,
      author_login: snap.authorLogin,
      head_ref: snap.headRef,
      base_ref: snap.baseRef,
      created_at_github: snap.createdAtGithub,
      updated_at_github: snap.updatedAtGithub,
      mergeable_state: snap.mergeableState,
      mergeable: snap.mergeable,
      additions: snap.additions,
      deletions: snap.deletions,
      changed_files: snap.changedFiles,
      commits: snap.commits,
      html_url: snap.htmlUrl,
      body: snap.body,
    })
    .returningAll()
    .executeTakeFirstOrThrow();
}

export async function markPrClosed(repoId: number, prNumber: number): Promise<void> {
  await db
    .updateTable('pull_requests')
    .set({ state: 'closed', last_synced_at: new Date() })
    .where('repo_id', '=', repoId)
    .where('number', '=', prNumber)
    .execute();
}

export interface ReviewRequestSnapshot {
  prId: number;
  reviewerLogin: string;
  requestedAt: Date;
  state: ReviewRequest['state'];
  reviewSubmittedAt: Date | null;
}

export async function upsertReviewRequest(
  snap: ReviewRequestSnapshot,
): Promise<{ prId: number; reviewerId: number; row: ReviewRequest }> {
  const reviewer = await upsertReviewer({ githubLogin: snap.reviewerLogin });

  const existing = await db
    .selectFrom('review_requests')
    .selectAll()
    .where('pr_id', '=', snap.prId)
    .where('reviewer_id', '=', reviewer.id)
    .executeTakeFirst();

  if (existing) {
    const row = await db
      .updateTable('review_requests')
      .set({
        state: snap.state,
        requested_at: snap.requestedAt,
        review_submitted_at: snap.reviewSubmittedAt,
      })
      .where('id', '=', existing.id)
      .returningAll()
      .executeTakeFirstOrThrow();
    return { prId: snap.prId, reviewerId: reviewer.id, row };
  }

  const row = await db
    .insertInto('review_requests')
    .values({
      pr_id: snap.prId,
      reviewer_id: reviewer.id,
      requested_at: snap.requestedAt,
      state: snap.state,
      review_submitted_at: snap.reviewSubmittedAt,
    })
    .returningAll()
    .executeTakeFirstOrThrow();
  return { prId: snap.prId, reviewerId: reviewer.id, row };
}

export interface OpenPrWithRepo extends Pr {
  repo_owner: string;
  repo_name: string;
}

export async function loadOpenPrs(): Promise<OpenPrWithRepo[]> {
  return db
    .selectFrom('pull_requests')
    .innerJoin('repos', 'repos.id', 'pull_requests.repo_id')
    .select([
      'pull_requests.id as id',
      'repo_id',
      'number',
      'title',
      'state',
      'draft',
      'author_login',
      'head_ref',
      'base_ref',
      'created_at_github',
      'updated_at_github',
      'mergeable_state',
      'mergeable',
      'additions',
      'deletions',
      'changed_files',
      'commits',
      'html_url',
      'body',
      'last_synced_at',
      'first_seen_at',
      'repos.owner as repo_owner',
      'repos.name as repo_name',
    ])
    .where('pull_requests.state', '=', 'open')
    .execute() as Promise<OpenPrWithRepo[]>;
}

export interface PendingReviewWithReviewer {
  rr_id: number;
  pr_id: number;
  pr_number: number;
  pr_title: string;
  pr_html_url: string;
  repo_full_name: string;
  reviewer_id: number;
  reviewer_login: string;
  reviewer_slack_id: string | null;
  requested_at: Date;
  pr_created_at_github: Date;
  additions: number;
  deletions: number;
  changed_files: number;
}

export async function loadPendingReviewRequests(): Promise<PendingReviewWithReviewer[]> {
  const rows = await db
    .selectFrom('review_requests')
    .innerJoin('reviewers', 'reviewers.id', 'review_requests.reviewer_id')
    .innerJoin('pull_requests', 'pull_requests.id', 'review_requests.pr_id')
    .innerJoin('repos', 'repos.id', 'pull_requests.repo_id')
    .select([
      'review_requests.id as rr_id',
      'review_requests.pr_id as pr_id',
      'pull_requests.number as pr_number',
      'pull_requests.title as pr_title',
      'pull_requests.html_url as pr_html_url',
      'pull_requests.additions as additions',
      'pull_requests.deletions as deletions',
      'pull_requests.changed_files as changed_files',
      'pull_requests.created_at_github as pr_created_at_github',
      'repos.full_name as repo_full_name',
      'reviewers.id as reviewer_id',
      'reviewers.github_login as reviewer_login',
      'reviewers.slack_user_id as reviewer_slack_id',
      'review_requests.requested_at as requested_at',
    ])
    .where('review_requests.state', '=', 'pending')
    .where('pull_requests.state', '=', 'open')
    .execute();

  return rows as unknown as PendingReviewWithReviewer[];
}

export async function loadReviewerOpenRequestCount(reviewerId: number): Promise<number> {
  const row = await db
    .selectFrom('review_requests')
    .innerJoin('pull_requests', 'pull_requests.id', 'review_requests.pr_id')
    .select((eb) => eb.fn.countAll().as('count'))
    .where('review_requests.reviewer_id', '=', reviewerId)
    .where('review_requests.state', '=', 'pending')
    .where('pull_requests.state', '=', 'open')
    .executeTakeFirstOrThrow();
  return Number((row as unknown as { count: string | number }).count);
}

export async function loadRecentFollowUpsForReviewer(
  reviewerId: number,
  since: Date,
): Promise<Array<{ sent_at: Date; channel: string; pr_id: number }>> {
  const rows = await db
    .selectFrom('follow_ups')
    .select(['sent_at', 'channel', 'pr_id'])
    .where('reviewer_id', '=', reviewerId)
    .where('sent_at', '>=', since)
    .orderBy('sent_at', 'desc')
    .execute();
  return rows as unknown as Array<{ sent_at: Date; channel: string; pr_id: number }>;
}

export async function hasRecentFollowUp(
  prId: number,
  reviewerId: number,
  sinceHours: number,
): Promise<boolean> {
  const since = new Date(Date.now() - sinceHours * 60 * 60 * 1000);
  const row = await db
    .selectFrom('follow_ups')
    .select((eb) => eb.fn.countAll().as('count'))
    .where('pr_id', '=', prId)
    .where('reviewer_id', '=', reviewerId)
    .where('sent_at', '>=', since)
    .executeTakeFirst();
  return Number((row as unknown as { count: string | number }).count) > 0;
}

export async function recordFollowUp(params: {
  prId: number;
  reviewerId: number;
  channel: 'slack' | 'teams' | 'github_comment';
  messageText: string | null;
  decisionReason: string;
  dryRun: boolean;
}): Promise<void> {
  await db
    .insertInto('follow_ups')
    .values({
      pr_id: params.prId,
      reviewer_id: params.reviewerId,
      channel: params.channel,
      message_text: params.messageText,
      sent_at: new Date(),
      decision_reason: params.decisionReason,
      dry_run: params.dryRun,
    })
    .execute();
}

export async function recordAuditEvent(eventType: string, payload: unknown): Promise<void> {
  await db
    .insertInto('audit_log')
    .values({ event_type: eventType, payload: JSON.stringify(payload) as unknown })
    .execute();
}

export async function getReviewerById(id: number): Promise<Reviewer | undefined> {
  return db.selectFrom('reviewers').selectAll().where('id', '=', id).executeTakeFirst();
}