/**
 * Dashboard queries — REAL
 *
 * All queries hit the real Postgres DB via Kysely. No mocks.
 * These are read-only queries used by the web UI to render the dashboard.
 *
 * MOCK DATA NOTE: The data returned includes mock bot reviewers and mock
 * review requests that were inserted manually (not from GitHub sync).
 * The repos, PRs, and branch protection data ARE real (synced from GitHub).
 * The follow-ups are real DB records, but their decision reasons were
 * generated by the mock cadence fallback (not the LLM).
 */
import { db } from '../db/client.js';

export interface DashboardRepoRow {
  id: number;
  full_name: string;
  default_branch: string | null;
  last_synced_at: Date | null;
  open_pr_count: number;
  required_approving_review_count: number | null;
  requires_code_owner_reviews: boolean | null;
}

export async function fetchDashboardRepos(): Promise<DashboardRepoRow[]> {
  const repos = await db
    .selectFrom('repos')
    .selectAll()
    .orderBy('full_name', 'asc')
    .execute();

  const prCounts = await db
    .selectFrom('pull_requests')
    .select(['repo_id', (eb) => eb.fn.countAll().as('open_pr_count')])
    .where('state', '=', 'open')
    .groupBy('repo_id')
    .execute();

  const prCountMap = new Map<number, number>();
  for (const r of prCounts as Array<{ repo_id: number; open_pr_count: string | number }>) {
    prCountMap.set(r.repo_id, Number(r.open_pr_count));
  }

  return repos.map((r) => ({
    id: r.id,
    full_name: r.full_name,
    default_branch: r.default_branch,
    last_synced_at: r.last_synced_at,
    open_pr_count: prCountMap.get(r.id) ?? 0,
    required_approving_review_count: r.required_approving_review_count,
    requires_code_owner_reviews: r.requires_code_owner_reviews,
  }));
}

export interface DashboardPrRow {
  id: number;
  number: number;
  title: string;
  state: string;
  draft: boolean;
  author_login: string;
  repo_full_name: string;
  head_ref: string;
  base_ref: string;
  updated_at_github: Date;
  created_at_github: Date;
  changed_files: number;
  additions: number;
  deletions: number;
  mergeable_state: string | null;
  html_url: string;
  pending_reviewers: string | null;
  required_approving_review_count: number | null;
  requires_code_owner_reviews: boolean | null;
}

export async function fetchDashboardPrs(): Promise<DashboardPrRow[]> {
  const rows = await db
    .selectFrom('pull_requests')
    .innerJoin('repos', 'repos.id', 'pull_requests.repo_id')
    .leftJoin('review_requests', 'review_requests.pr_id', 'pull_requests.id')
    .leftJoin('reviewers', 'reviewers.id', 'review_requests.reviewer_id')
    .select([
      'pull_requests.id as id',
      'pull_requests.number as number',
      'pull_requests.title as title',
      'pull_requests.state as state',
      'pull_requests.draft as draft',
      'pull_requests.author_login as author_login',
      'pull_requests.head_ref as head_ref',
      'pull_requests.base_ref as base_ref',
      'pull_requests.updated_at_github as updated_at_github',
      'pull_requests.created_at_github as created_at_github',
      'pull_requests.changed_files as changed_files',
      'pull_requests.additions as additions',
      'pull_requests.deletions as deletions',
      'pull_requests.mergeable_state as mergeable_state',
      'pull_requests.html_url as html_url',
      'repos.full_name as repo_full_name',
      'repos.required_approving_review_count as required_approving_review_count',
      'repos.requires_code_owner_reviews as requires_code_owner_reviews',
    ])
    .where('pull_requests.state', '=', 'open')
    .orderBy('pull_requests.updated_at_github', 'desc')
    .execute();

  const byId = new Map<number, DashboardPrRow>();
  for (const r of rows as Array<Record<string, unknown>>) {
    const id = r.id as number;
    if (!byId.has(id)) {
      byId.set(id, {
        id,
        number: r.number as number,
        title: r.title as string,
        state: r.state as string,
        draft: r.draft as boolean,
        author_login: r.author_login as string,
        repo_full_name: r.repo_full_name as string,
        head_ref: r.head_ref as string,
        base_ref: r.base_ref as string,
        updated_at_github: r.updated_at_github as Date,
        created_at_github: r.created_at_github as Date,
        changed_files: r.changed_files as number,
        additions: r.additions as number,
        deletions: r.deletions as number,
        mergeable_state: r.mergeable_state as string | null,
        html_url: r.html_url as string,
        pending_reviewers: null,
        required_approving_review_count: r.required_approving_review_count as number | null,
        requires_code_owner_reviews: r.requires_code_owner_reviews as boolean | null,
      });
    }
  }

  const reviewerRows = await db
    .selectFrom('review_requests')
    .innerJoin('reviewers', 'reviewers.id', 'review_requests.reviewer_id')
    .select(['review_requests.pr_id as pr_id', 'reviewers.github_login as login', 'review_requests.state as state'])
    .where('review_requests.state', '=', 'pending')
    .execute();

  const reviewersByPr = new Map<number, string[]>();
  for (const rr of reviewerRows as Array<{ pr_id: number; login: string }>) {
    const list = reviewersByPr.get(rr.pr_id) ?? [];
    list.push(rr.login);
    reviewersByPr.set(rr.pr_id, list);
  }
  for (const [prId, logins] of reviewersByPr) {
    const pr = byId.get(prId);
    if (pr) pr.pending_reviewers = logins.join(', ');
  }

  return [...byId.values()];
}

export interface DashboardReviewerRow {
  id: number;
  github_login: string;
  slack_user_id: string | null;
  open_requests: number;
  recent_follow_ups: number;
  is_human: boolean;
}

export async function fetchDashboardReviewers(): Promise<DashboardReviewerRow[]> {
  const rows = await db
    .selectFrom('reviewers')
    .leftJoin('review_requests', 'review_requests.reviewer_id', 'reviewers.id')
    .leftJoin('pull_requests', 'pull_requests.id', 'review_requests.pr_id')
    .select([
      'reviewers.id as id',
      'reviewers.github_login as github_login',
      'reviewers.slack_user_id as slack_user_id',
    ])
    .select((eb) => eb.fn.count('review_requests.id').as('open_requests'))
    .where('review_requests.state', '=', 'pending')
    .where('pull_requests.state', '=', 'open')
    .groupBy(['reviewers.id', 'reviewers.github_login', 'reviewers.slack_user_id'])
    .execute();

  const since = new Date(Date.now() - 24 * 60 * 60 * 1000);
  const followRows = await db
    .selectFrom('follow_ups')
    .select(['reviewer_id', (eb) => eb.fn.count('follow_ups.id').as('count')])
    .where('sent_at', '>=', since)
    .groupBy('reviewer_id')
    .execute();

  const followMap = new Map<number, number>();
  for (const f of followRows as Array<{ reviewer_id: number; count: string }>) {
    followMap.set(f.reviewer_id, Number(f.count));
  }

  const result = (rows as Array<Record<string, unknown>>).map((r) => {
    const login = r.github_login as string;
    return {
      id: r.id as number,
      github_login: login,
      slack_user_id: (r.slack_user_id as string | null) ?? null,
      open_requests: Number(r.open_requests ?? 0),
      recent_follow_ups: followMap.get(r.id as number) ?? 0,
      is_human: !login.endsWith('-bot'),
    };
  });

  result.sort((a, b) => {
    if (a.is_human !== b.is_human) return a.is_human ? -1 : 1;
    return a.github_login.localeCompare(b.github_login);
  });

  return result;
}

export interface DashboardFollowUpRow {
  id: number;
  sent_at: Date;
  channel: string;
  message_text: string | null;
  decision_reason: string;
  dry_run: boolean;
  pr_number: number;
  repo_full_name: string;
  reviewer_login: string;
}

export async function fetchRecentFollowUps(limit = 50): Promise<DashboardFollowUpRow[]> {
  const rows = await db
    .selectFrom('follow_ups')
    .innerJoin('pull_requests', 'pull_requests.id', 'follow_ups.pr_id')
    .innerJoin('repos', 'repos.id', 'pull_requests.repo_id')
    .innerJoin('reviewers', 'reviewers.id', 'follow_ups.reviewer_id')
    .select([
      'follow_ups.id as id',
      'follow_ups.sent_at as sent_at',
      'follow_ups.channel as channel',
      'follow_ups.message_text as message_text',
      'follow_ups.decision_reason as decision_reason',
      'follow_ups.dry_run as dry_run',
      'pull_requests.number as pr_number',
      'repos.full_name as repo_full_name',
      'reviewers.github_login as reviewer_login',
    ])
    .orderBy('follow_ups.sent_at', 'desc')
    .limit(limit)
    .execute();

  return rows as unknown as DashboardFollowUpRow[];
}

export async function fetchStats(): Promise<{
  openPrs: number;
  pendingReviews: number;
  reviewers: number;
  followUps24h: number;
  trackedRepos: number;
  lastSyncedAt: Date | null;
}> {
  const [openPrsRow, pendingRow, reviewersRow, followUpsRow, repoRow, trackedReposRow] = await Promise.all([
    db
      .selectFrom('pull_requests')
      .select((eb) => eb.fn.countAll().as('count'))
      .where('state', '=', 'open')
      .executeTakeFirst(),
    db
      .selectFrom('review_requests')
      .innerJoin('pull_requests', 'pull_requests.id', 'review_requests.pr_id')
      .select((eb) => eb.fn.countAll().as('count'))
      .where('review_requests.state', '=', 'pending')
      .where('pull_requests.state', '=', 'open')
      .executeTakeFirst(),
    db.selectFrom('reviewers').select((eb) => eb.fn.countAll().as('count')).executeTakeFirst(),
    db
      .selectFrom('follow_ups')
      .select((eb) => eb.fn.countAll().as('count'))
      .where('sent_at', '>=', new Date(Date.now() - 24 * 60 * 60 * 1000))
      .executeTakeFirst(),
    db.selectFrom('repos').select('last_synced_at').orderBy('last_synced_at', 'desc').limit(1).executeTakeFirst(),
    db.selectFrom('repos').select((eb) => eb.fn.countAll().as('count')).executeTakeFirst(),
  ]);

  return {
    openPrs: Number((openPrsRow as { count: string | number }).count ?? 0),
    pendingReviews: Number((pendingRow as { count: string | number }).count ?? 0),
    reviewers: Number((reviewersRow as { count: string | number }).count ?? 0),
    followUps24h: Number((followUpsRow as { count: string | number }).count ?? 0),
    trackedRepos: Number((trackedReposRow as { count: string | number }).count ?? 0),
    lastSyncedAt: (repoRow as { last_synced_at: Date | null } | undefined)?.last_synced_at ?? null,
  };
}